# Use postgres/example user/password credentials

services:

  db:
    image: postgres:16
    container_name: postgres_db_inmobiliaria
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./inmo_con_datos.sql:/docker-entrypoint-initdb.d/init_db.sql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: administrador
      POSTGRES_DB: inmo
    ports:
      - "0.0.0.0:5432:5432"
  adminer:
    container_name: adminer_ui_inmo
    image: adminer
    restart: always
    ports:
      - "0.0.0.0:8082:8080"
